import * as Dialog from '@radix-ui/react-dialog';
import * as RadioGroup from '@radix-ui/react-radio-group';
import { Button, Chip, IconButton, NamedProgress, SelectionControl, StatusBadge, TextField } from '../atoms';
import { ChargeIcon } from '../icons';
import { Alert, AppBar, CommandProgress, DetailPanel, EmptyState, SettingRow, StationCard, StatusPanel, WalletCard } from '../molecules';

export function BottomNav({ active = 'home', state = 'visible' }: { active?: 'home' | 'wallet' | 'sessions' | 'profile'; state?: 'visible' | 'badge' | 'disabled' | 'hidden' }) {
  if (state === 'hidden') return <div className="ac-nav-hidden">Navigation hidden during focused task</div>;
  const labels = { home: 'Home', wallet: 'Wallet', sessions: 'Sessions', profile: 'Profile' } as const;
  return <nav className="ac-bottom-nav" aria-label="Primary" data-state={state}>{(['home', 'wallet', 'sessions', 'profile'] as const).map((item) => <button type="button" key={item} data-active={active === item} aria-current={active === item ? 'page' : undefined} disabled={state === 'disabled'}><ChargeIcon name={item === 'home' ? 'home' : item === 'wallet' ? 'wallet' : item === 'sessions' ? 'flash' : 'user'} /><small>{labels[item]}</small>{state === 'badge' && item === 'sessions' && <b aria-label="1 new session update">1</b>}</button>)}</nav>;
}

export function ModalSheet({ variant = 'information', state = 'default', onConfirm, onDismiss, manageFocus = true }: { variant?: 'information' | 'selection' | 'confirmation' | 'destructive'; state?: 'default' | 'loading' | 'error'; onConfirm?: () => void; onDismiss?: () => void; manageFocus?: boolean }) {
  return <Dialog.Root defaultOpen modal={manageFocus} onOpenChange={(open) => { if (!open) onDismiss?.(); }}>{manageFocus && <Dialog.Overlay className="ac-dialog-overlay" />}<Dialog.Content className="ac-sheet" data-variant={variant} aria-modal={manageFocus || undefined} aria-busy={state === 'loading' || undefined} onEscapeKeyDown={onDismiss ? undefined : (event) => event.preventDefault()}><span className="ac-sheet__grabber" aria-hidden /><Dialog.Title>{variant === 'destructive' ? 'Delete account?' : variant === 'confirmation' ? 'Confirm this action' : variant === 'selection' ? 'Choose an option' : 'Before you continue'}</Dialog.Title><Dialog.Description role={state === 'error' ? 'alert' : undefined}>{state === 'error' ? 'The request failed. Your current state has not changed. Try again or cancel.' : variant === 'destructive' ? 'This permanently removes your profile after all blockers are resolved.' : 'Review the details and choose the next safe action.'}</Dialog.Description>{state === 'loading' ? <NamedProgress label="Processing request" /> : <div className="ac-sheet__actions"><Button variant={variant === 'destructive' ? 'destructive' : 'primary'} onClick={onConfirm}>{variant === 'destructive' ? 'Delete account' : 'Continue'}</Button><Button variant="secondary" onClick={onDismiss}>Cancel</Button></div>}</Dialog.Content></Dialog.Root>;
}

export function LaunchGate({ state = 'checking' }: { state?: 'checking' | 'offline' | 'timeout' | 'update-required' | 'store-failure' | 'resumable' }) {
  return <section className="ac-launch"><div className="ac-wordmark">Atlas<br /><span>CHARGE</span></div>{state === 'checking' ? <NamedProgress label="Checking your session" /> : <StatusPanel kind="account" state={state} title={state === 'update-required' ? 'Update Atlas Charge' : state === 'offline' ? 'You are offline' : 'We could not finish launching'} detail={state === 'resumable' ? 'Your last safe step is ready to resume.' : 'Your charging session is safe. Try again when the connection returns.'} tone={state === 'update-required' ? 'warning' : state === 'resumable' ? 'info' : 'danger'} action={state === 'update-required' ? 'Open store' : 'Try again'} />}</section>;
}

export function ProfileForm({ state = 'view' }: { state?: 'view' | 'edit' | 'validating' | 'saving' | 'saved' | 'field-error' | 'save-failed' | 'verified' }) {
  return <form className="ac-form" onSubmit={(event) => event.preventDefault()}><AppBar title="Profile" mode="back" /><TextField label="Mobile number" value="+91 98765 43210" state="verified" message="Verified identity field" /><TextField label="Full name" value="Ananya Sharma" state={state === 'field-error' ? 'error' : state === 'view' || state === 'verified' ? 'read-only' : 'filled'} message={state === 'field-error' ? 'Enter your full name' : undefined} /><TextField label="Email" value="ananya@example.com" state={state === 'view' ? 'read-only' : 'valid'} />{state === 'save-failed' && <Alert tone="danger" title="Profile was not saved" body="Your valid changes are still here." action="Retry" />}<Button type="submit" width="full" state={state === 'saving' || state === 'validating' ? 'loading' : 'default'}>{state === 'saved' ? 'Saved' : 'Save profile'}</Button></form>;
}

export function LegalViewer({ state = 'current' }: { state?: 'current' | 'updated' | 'cached' | 'failed' | 'update-available' }) {
  return <article className="ac-legal"><AppBar title="Privacy policy" mode="back" />{state === 'updated' && <Alert tone="info" title="Updated since you accepted" body="Review the highlighted changes." />}{state === 'cached' && <Alert tone="warning" title="Offline copy" body="Showing the latest saved version." />}{state === 'failed' ? <EmptyState variant="failed" title="Policy could not load" action="Try again" /> : <><small>Effective 12 August 2026 · Version 2.1</small><h3>Your charging data</h3><p>Atlas uses account, charger, session and payment references to provide charging and support. External links open separately and never replace this document without warning.</p>{state === 'update-available' && <SettingRow title="App update available" detail="Version 4.2.0" mode="status" state="granted" />}</>}</article>;
}

export function QrScanner({ state = 'ready' }: { state?: 'requesting' | 'ready' | 'checking' | 'invalid' | 'unreadable' | 'denied' | 'offline' | 'timeout' }) {
  return <section className="ac-scanner"><AppBar title="Scan QR to charge" mode="close" /><div className="ac-scanner__viewport" data-state={state}><span className="ac-scanner__corners" aria-hidden /><span className="ac-scanner__beam" aria-hidden /><strong aria-hidden><ChargeIcon name="qr" /></strong></div><p>{state === 'requesting' ? 'Requesting camera access…' : state === 'checking' ? 'Charger detected. Checking…' : state === 'invalid' ? 'This is not a Atlas charger code.' : state === 'unreadable' ? 'We cannot read that code. Clean the label or enter the ID.' : state === 'denied' ? 'Camera access is denied. Open Settings or enter the charger ID.' : state === 'offline' ? 'A connection is required to validate this charger.' : state === 'timeout' ? 'Validation timed out. Try again.' : 'Place the charger QR code inside the frame.'}</p><div className="ac-scanner__actions"><IconButton icon="flashlight" label="Flashlight" /><Button variant="secondary">Enter charger ID</Button></div></section>;
}

export function ChargerDetail({ state = 'ready' }: { state?: 'loading' | 'ready' | 'unavailable' | 'unknown' | 'failed' | 'price-changed' | 'partial' }) {
  return <section className="ac-charger-detail"><div className="ac-map-canvas"><span>Map context</span></div><div className="ac-charger-detail__sheet"><span className="ac-sheet__grabber" /><DetailPanel variant="station-header" state={state} />{state === 'failed' ? <Alert tone="danger" title="Details could not load" action="Retry" /> : <><DetailPanel variant="specification" state={state === 'partial' ? 'partial data' : state} /><DetailPanel variant="connector" state={state} />{state === 'price-changed' && <Alert tone="warning" title="Tariff changed" body="Review the new estimate before starting." />}</>}<Button width="full" state={state === 'ready' || state === 'price-changed' ? 'default' : 'disabled'}>Review and start</Button></div></section>;
}

export function StartReadiness({ state = 'ready' }: { state?: 'ready' | 'data-changed' | 'unavailable' | 'insufficient' | 'stale' | 'starting' }) {
  return <section className="ac-readiness"><AppBar title="Review charging" mode="back" /><StationCard state={state === 'unavailable' ? 'offline' : 'available'} stale={state === 'stale'} /><DetailPanel variant="duration" /><WalletCard variant="readiness" state={state === 'insufficient' ? 'shortfall' : 'sufficient'} />{state === 'data-changed' && <Alert tone="warning" title="Details changed" body="Review the latest tariff and availability." />}{state === 'starting' ? <CommandProgress stage={2} /> : <Button width="full" state={state === 'ready' || state === 'data-changed' ? 'default' : 'disabled'}>Start charging</Button>}</section>;
}

export function ActiveSession({ state = 'active' }: { state?: 'starting' | 'active' | 'delayed' | 'stale' | 'interrupted' | 'stopping' | 'ending' | 'unknown' }) {
  const unavailable = state === 'unknown' || state === 'starting';
  const delayed = state === 'stale' || state === 'delayed';
  const metricPrefix = delayed ? 'Last reported ' : '';
  return <section className="ac-session"><AppBar title="Charging session" mode="action" /><StatusBadge tone={state === 'active' ? 'success' : state === 'interrupted' ? 'danger' : delayed ? 'warning' : 'info'}>{state}</StatusBadge><div className="ac-session__metric" aria-live="polite"><strong>{unavailable ? '—' : '18 min'}</strong><span>{unavailable ? 'Elapsed time unavailable' : `${metricPrefix}elapsed time`}</span></div><div className="ac-session__stats" data-stale={delayed || undefined}><span><b>{unavailable ? '—' : '12.4 kWh'}</b><small>{unavailable ? 'Energy unavailable' : `${metricPrefix}energy delivered`}</small></span><span><b>{unavailable ? '—' : '₹224'}</b><small>{unavailable ? 'Cost unavailable' : `${metricPrefix}estimated cost`}</small></span><span><b>{unavailable ? '—' : '2 min ago'}</b><small>{unavailable ? 'Last update unavailable' : 'Last update'}</small></span></div>{delayed && <Alert tone="warning" title="Session data is delayed" body="These are the last reported values. The charger may still be delivering power." action="Refresh" />}{state === 'unknown' && <Alert tone="warning" title="Live session data is unavailable" body="Do not rely on the displayed totals. Refresh or contact support before taking another action." action="Refresh" />}{state === 'interrupted' && <Alert tone="danger" title="Charging was interrupted" body="Power stopped unexpectedly." action="Get help" />}{state === 'stopping' || state === 'ending' ? <CommandProgress stage={3} state={state === 'stopping' ? 'delayed' : 'active'} /> : <div className="ac-session__actions"><Button width="full" state={unavailable ? 'disabled' : 'default'}>Stop charging</Button><Button variant="secondary" width="full">Get help</Button></div>}</section>;
}

export function SessionSummary({ state = 'final' }: { state?: 'final' | 'provisional' | 'payment-pending' | 'adjusted' | 'invoice-unavailable' | 'share-failed' }) {
  return <section className="ac-summary"><AppBar title="Session summary" mode="close" /><StatusBadge tone={state === 'final' ? 'success' : state === 'payment-pending' || state === 'provisional' ? 'warning' : state === 'invoice-unavailable' || state === 'share-failed' ? 'danger' : 'info'}>{state}</StatusBadge><h3>{state === 'final' ? '₹248 total' : '₹248 estimated total'}</h3><dl><div><dt>Session</dt><dd>SES-842019</dd></div><div><dt>Duration</dt><dd>42 min</dd></div><div><dt>Energy</dt><dd>13.2 kWh</dd></div><div><dt>Tariff</dt><dd>₹18/kWh</dd></div><div><dt>Tax</dt><dd>₹10.40</dd></div></dl>{state === 'provisional' && <Alert tone="warning" title="Values are provisional" body="The final charger record is still reconciling." />}{state === 'invoice-unavailable' && <Alert tone="danger" title="Invoice unavailable" action="Notify me" />}<div className="ac-summary__actions"><Button variant="secondary">Download invoice</Button><Button variant="secondary">Report an issue</Button></div></section>;
}

export function FilterSheet({ state = 'default', onDismiss, manageFocus = true }: { state?: 'default' | 'selected' | 'applied' | 'no-results' | 'reset'; onDismiss?: () => void; manageFocus?: boolean }) {
  const hasCriteria = state === 'selected' || state === 'applied' || state === 'no-results';
  return <Dialog.Root defaultOpen modal={manageFocus} onOpenChange={(open) => { if (!open) onDismiss?.(); }}>{manageFocus && <Dialog.Overlay className="ac-dialog-overlay" />}<Dialog.Content className="ac-sheet ac-filter-sheet" data-state={state} onEscapeKeyDown={onDismiss ? undefined : (event) => event.preventDefault()}><span className="ac-sheet__grabber" aria-hidden /><Dialog.Title className="ac-visually-hidden">Filter and sort</Dialog.Title><AppBar title="Filter and sort" mode="close" onClose={onDismiss} />{state === 'applied' && <Alert tone="success" title="2 filters applied" body="Available · Nearby" />}{state === 'reset' && <Alert tone="info" title="Filters reset" body="Showing all stations." />}<h4>Status</h4><div className="ac-chip-row">{['Available', 'Nearby', 'Fast', 'Open now'].map((label, index) => <Chip key={label} selected={hasCriteria && index < 2}>{label}</Chip>)}</div><h4>Sort by</h4><RadioGroup.Root className="ac-filter-sheet__sort" name="sort" defaultValue="nearest" aria-label="Sort stations"><label className="ac-selection"><RadioGroup.Item className="ac-selection__mark" value="nearest"><RadioGroup.Indicator className="ac-selection__indicator"><ChargeIcon name="circle" strokeWidth={3} /></RadioGroup.Indicator></RadioGroup.Item><span>Nearest first</span></label><label className="ac-selection"><RadioGroup.Item className="ac-selection__mark" value="price"><RadioGroup.Indicator className="ac-selection__indicator"><ChargeIcon name="circle" strokeWidth={3} /></RadioGroup.Indicator></RadioGroup.Item><span>Lowest price</span></label></RadioGroup.Root><div className="ac-sheet__actions"><Button variant="secondary">Reset</Button><Button>Apply filters</Button></div>{state === 'no-results' && <EmptyState variant="filtered" title="No matching results" action="Reset filters" />}</Dialog.Content></Dialog.Root>;
}

export function TicketForm({ state = 'draft' }: { state?: 'draft' | 'validating' | 'submitting' | 'delayed' | 'submitted' | 'failed' }) {
  return <form className="ac-form" onSubmit={(event) => event.preventDefault()}><AppBar title="Report an issue" mode="back" /><StatusPanel kind="ticket" state="Context attached" title="Session SES-842019" detail="Atlas Community Charger · payment ₹248" tone="info" /><TextField label="Issue type" value="Charging stopped unexpectedly" state="filled" /><TextField label="What happened?" placeholder="Describe the issue and what you already tried" state={state === 'validating' ? 'error' : 'empty'} message={state === 'validating' ? 'Add enough detail for support to act' : 'Your draft is kept if submission fails'} />{state === 'failed' && <Alert tone="danger" title="Ticket was not submitted" body="Your draft is safe." action="Retry" />}{state === 'submitted' ? <StatusPanel kind="ticket" state="Submitted" title="Ticket VC-20481" detail="Support will respond within 4 working hours." tone="success" action="Back to session" /> : <Button type="submit" width="full" state={state === 'submitting' || state === 'delayed' ? 'loading' : 'default'}>Submit ticket</Button>}</form>;
}

export function RequestChargerForm({ state = 'draft' }: { state?: 'draft' | 'location-denied' | 'validation-error' | 'saving' | 'ready' | 'submitting' | 'submitted' | 'delayed' | 'duplicate' | 'failed' }) {
  if (state === 'submitted' || state === 'duplicate') return <StatusPanel kind="request" state={state} title={state === 'duplicate' ? 'We already have this request' : 'Request received'} detail="Reference RQ-10482. This is an expression of interest, not an installation commitment." tone={state === 'duplicate' ? 'info' : 'success'} action="Done" />;
  return <form className="ac-form" onSubmit={(event) => event.preventDefault()}><AppBar title="Request a charger" mode="back" /><p>Tell us where community charging would help. Submission does not guarantee installation.</p><TextField label="Property type" value="Apartment community" state="filled" /><TextField label="Address or current location" state={state === 'location-denied' || state === 'validation-error' ? 'error' : 'empty'} message={state === 'location-denied' ? 'Location access is off. Enter the address manually.' : state === 'validation-error' ? 'Enter a complete address' : undefined} /><TextField label="Community size" placeholder="Number of homes" inputMode="numeric" /><TextField label="EV count" placeholder="Approximate number" inputMode="numeric" /><SelectionControl label="I agree to be contacted about this request" checked={state === 'ready'} state={state === 'validation-error' ? 'error' : 'default'} /><Button type="submit" width="full" state={state === 'saving' || state === 'submitting' || state === 'delayed' ? 'loading' : 'default'}>Submit interest</Button>{state === 'failed' && <Alert tone="danger" title="Request not submitted" body="Your draft is saved." action="Retry" />}</form>;
}
