import type { TokenDef, TokenLayerDef, TokenType } from '../../../tokens/types';

const semantic = (path: string) => ({ layer: 'semantic' as const, path });
const alias = (path: string, type: TokenType, target: string): TokenDef => ({
  path,
  type,
  alias: semantic(target),
});
const color = (path: string, target: string): TokenDef => alias(path, 'color', target);
const dimension = (path: string, value: number): TokenDef => ({ path, type: 'dimension', value });
const dimensionAlias = (path: string, target: string): TokenDef => alias(path, 'dimension', target);
const numberAlias = (path: string, target: string): TokenDef => alias(path, 'number', target);
const shadow = (path: string, target: string): TokenDef => alias(path, 'shadow', target);
const duration = (path: string, target: string): TokenDef => alias(path, 'duration', target);
const string = (path: string, target: string): TokenDef => alias(path, 'string', target);

/**
 * Component tokens intentionally describe a component and one of its slots.
 * Geometry that defines anatomy (pills and fixed controls) is local; themeable
 * container geometry aliases semantic radius roles. This prevents a radius or
 * spacing change intended for one family from leaking into every component.
 */
export const ATLAS_CHARGE_COMPONENT_TOKENS: TokenLayerDef = {
  layer: 'component',
  tokens: [
    // Actions
    dimension('button.height', 52),
    dimension('button.height-compact', 48),
    dimension('button.padding-x', 20),
    dimension('button.gap', 8),
    dimension('button.radius', 999),
    dimensionAlias('button.font-size', 'text.label'),
    numberAlias('button.font-weight', 'font.weight-medium'),
    color('button.primary.bg', 'accent.9'),
    color('button.primary.bg-hover', 'accent.10'),
    color('button.primary.text', 'accent.contrast'),
    color('button.secondary.bg', 'color.surface'),
    color('button.secondary.bg-hover', 'color.surface-muted'),
    color('button.secondary.text', 'color.text'),
    color('button.secondary.border', 'color.border'),
    color('button.tertiary.text', 'color.text'),
    color('button.destructive.bg', 'color.surface'),
    color('button.destructive.text', 'status.danger'),
    color('button.destructive.border', 'color.border'),
    color('button.disabled.bg', 'color.surface-muted'),
    color('button.disabled.text', 'color.text-secondary'),
    color('button.focus-ring', 'color.focus-ring'),
    duration('button.transition-duration', 'motion.interaction.duration'),
    string('button.transition-easing', 'motion.interaction.easing'),

    dimension('spinner.size', 16),
    dimension('spinner.stroke', 2),
    duration('spinner.duration', 'motion.spinner.duration'),

    dimension('icon-button.size', 44),
    dimension('icon-button.font-size', 20),
    color('icon-button.bg', 'color.surface'),
    color('icon-button.text', 'color.text'),
    color('icon-button.border', 'color.border'),
    color('icon-button.selected-bg', 'accent.9'),
    color('icon-button.selected-text', 'accent.contrast'),
    color('icon-button.disabled-bg', 'color.surface-muted'),
    color('icon-button.disabled-text', 'color.text-secondary'),
    color('icon-button.focus-ring', 'color.focus-ring'),
    duration('icon-button.transition-duration', 'motion.interaction.duration'),
    string('icon-button.transition-easing', 'motion.interaction.easing'),

    // Inputs and selection controls
    dimension('field.width', 340),
    dimension('field.gap', 6),
    dimension('field.control-height', 52),
    dimension('field.padding-x', 16),
    dimension('field.trailing-space', 42),
    dimension('field.mark-icon-size', 18),
    dimensionAlias('field.radius', 'radius.interactive'),
    dimensionAlias('field.label-font-size', 'text.label'),
    dimensionAlias('field.input-font-size', 'text.body'),
    dimension('field.mobile-font-size', 16),
    dimensionAlias('field.message-font-size', 'text.caption'),
    numberAlias('field.label-font-weight', 'font.weight-medium'),
    color('field.text', 'color.text'),
    color('field.message-text', 'color.text-secondary'),
    color('field.bg', 'color.surface'),
    color('field.border', 'color.border'),
    color('field.focus-border', 'accent.9'),
    color('field.error', 'status.danger'),
    color('field.success', 'status.success'),
    color('field.disabled-bg', 'color.surface-muted'),
    color('field.disabled-text', 'color.text-secondary'),

    dimension('otp.gap', 12),
    dimension('otp.cell-gap', 8),
    dimension('otp.cell-width', 42),
    dimension('otp.cell-height', 50),
    dimensionAlias('otp.cell-radius', 'radius.interactive'),
    dimensionAlias('otp.font-size', 'text.title'),
    numberAlias('otp.font-weight', 'font.weight-bold'),
    color('otp.bg', 'color.surface'),
    color('otp.border', 'color.border'),
    color('otp.focus-ring', 'color.focus-ring'),
    color('otp.error-border', 'status.danger'),
    color('otp.help-text', 'color.text-secondary'),

    dimension('selection.min-height', 44),
    dimension('selection.gap', 10),
    dimension('selection.mark-size', 22),
    dimension('selection.mark-radius', 6),
    dimension('selection.mark-font-size', 12),
    dimension('selection.mark-icon-size', 14),
    dimensionAlias('selection.font-size', 'text.body'),
    color('selection.text', 'color.text'),
    color('selection.border', 'color.border-strong'),
    color('selection.bg', 'color.surface'),
    color('selection.checked-bg', 'accent.9'),
    color('selection.checked-text', 'accent.contrast'),
    color('selection.focus-ring', 'color.focus-ring'),
    color('selection.error-text', 'status.danger'),
    color('selection.disabled-text', 'color.text-secondary'),

    dimension('toggle.width', 44),
    dimension('toggle.height', 24),
    dimension('toggle.thumb-size', 18),
    dimension('toggle.thumb-inset', 3),
    dimension('toggle.thumb-translation', 20),
    dimension('toggle.radius', 999),
    color('toggle.off-bg', 'color.border-strong'),
    color('toggle.on-bg', 'accent.9'),
    color('toggle.thumb-bg', 'color.surface'),
    color('toggle.focus-ring', 'color.focus-ring'),
    color('toggle.error-ring', 'status.danger'),
    duration('toggle.transition-duration', 'motion.interaction.duration'),
    string('toggle.transition-easing', 'motion.interaction.easing'),

    dimension('chip.height', 44),
    dimension('chip.padding-x', 16),
    dimension('chip.radius', 999),
    dimensionAlias('chip.font-size', 'text.label'),
    numberAlias('chip.font-weight', 'font.weight-medium'),
    color('chip.bg', 'color.surface'),
    color('chip.text', 'color.text'),
    color('chip.border', 'color.border'),
    color('chip.selected-bg', 'accent.9'),
    color('chip.selected-text', 'accent.contrast'),
    color('chip.disabled-bg', 'color.surface-muted'),
    color('chip.disabled-text', 'color.text-secondary'),
    color('chip.focus-ring', 'color.focus-ring'),

    // Status and feedback
    dimension('status-badge.gap', 6),
    dimension('status-badge.padding-x', 9),
    dimension('status-badge.padding-y', 5),
    dimension('status-badge.radius', 999),
    dimension('status-badge.icon-size', 8),
    dimensionAlias('status-badge.font-size', 'text.caption'),
    numberAlias('status-badge.font-weight', 'font.weight-medium'),
    color('status-badge.neutral.bg', 'color.surface-muted'),
    color('status-badge.neutral.text', 'color.text'),
    color('status-badge.info.bg', 'status.info-bg'),
    color('status-badge.info.text', 'status.info-text'),
    color('status-badge.success.bg', 'status.success-bg'),
    color('status-badge.success.text', 'status.success-text'),
    color('status-badge.warning.bg', 'status.warning-bg'),
    color('status-badge.warning.text', 'status.warning-text'),
    color('status-badge.danger.bg', 'status.danger-bg'),
    color('status-badge.danger.text', 'status.danger-text'),
    color('status-badge.unknown.bg', 'color.surface-muted'),
    color('status-badge.unknown.text', 'color.text-secondary'),

    dimension('named-progress.gap', 12),
    dimension('named-progress.icon-size', 28),
    dimension('named-progress.icon-glyph-size', 16),
    numberAlias('named-progress.icon-weight', 'font.weight-bold'),
    color('named-progress.text', 'color.text'),
    color('named-progress.secondary-text', 'color.text-secondary'),
    color('named-progress.icon-bg', 'color.surface'),
    color('named-progress.icon-border', 'color.border'),
    color('named-progress.complete-bg', 'accent.9'),
    color('named-progress.complete-text', 'accent.contrast'),
    color('named-progress.failed-bg', 'status.danger-bg'),
    color('named-progress.failed-text', 'status.danger'),
    color('named-progress.delayed-text', 'status.warning'),

    dimension('alert.width', 520),
    dimension('alert.icon-column', 32),
    dimension('alert.icon-size', 28),
    dimension('alert.icon-glyph-size', 16),
    dimension('alert.gap', 10),
    dimension('alert.padding-x', 14),
    dimension('alert.padding-y', 12),
    dimensionAlias('alert.radius', 'radius.interactive'),
    numberAlias('alert.icon-weight', 'font.weight-bold'),
    numberAlias('alert.action-weight', 'font.weight-medium'),
    color('alert.text', 'color.text'),
    color('alert.secondary-text', 'color.text-secondary'),
    color('alert.icon-text', 'color.surface'),
    color('alert.border', 'color.border'),
    color('alert.focus-ring', 'color.focus-ring'),

    dimension('empty-state.width', 420),
    dimension('empty-state.padding', 32),
    dimension('empty-state.gap', 8),
    dimension('empty-state.symbol-size', 76),
    dimension('empty-state.symbol-font-size', 34),
    color('empty-state.symbol-bg', 'color.surface-muted'),
    color('empty-state.secondary-text', 'color.text-secondary'),

    dimension('coachmark.width', 260),
    dimension('coachmark.padding', 16),
    dimension('coachmark.gap', 12),
    dimensionAlias('coachmark.radius', 'radius.interactive'),
    color('coachmark.bg', 'accent.9'),
    color('coachmark.text', 'accent.contrast'),
    color('coachmark.focus-ring', 'color.focus-ring'),
    shadow('coachmark.shadow', 'elevation.transient'),

    // Navigation and discovery
    dimension('app-bar.side-column', 48),
    dimension('app-bar.min-height', 56),
    dimensionAlias('app-bar.title-font-size', 'text.title'),
    numberAlias('app-bar.title-weight', 'font.weight-semibold'),
    numberAlias('app-bar.action-weight', 'font.weight-medium'),
    color('app-bar.bg', 'color.bg'),
    color('app-bar.scrolled-bg', 'color.surface'),
    color('app-bar.text', 'color.text'),
    color('app-bar.border', 'color.border'),
    color('app-bar.focus-ring', 'color.focus-ring'),

    dimension('search.width', 520),
    dimension('search.gap', 10),
    dimension('search.padding-leading', 16),
    dimension('search.padding-compact', 6),
    dimension('search.help-padding-x', 8),
    dimension('search.radius', 999),
    dimension('search.mobile-font-size', 16),
    color('search.bg', 'color.surface'),
    color('search.text', 'color.text'),
    color('search.secondary-text', 'color.text-secondary'),
    color('search.border', 'color.border'),
    color('search.focus-border', 'accent.9'),
    color('search.error-border', 'status.danger'),

    dimension('bottom-nav.width', 390),
    dimension('bottom-nav.padding', 8),
    dimension('bottom-nav.item-height', 54),
    dimension('bottom-nav.item-padding', 6),
    dimension('bottom-nav.item-gap', 2),
    dimension('bottom-nav.icon-font-size', 20),
    dimensionAlias('bottom-nav.label-font-size', 'text.caption'),
    dimension('bottom-nav.indicator-width', 32),
    dimension('bottom-nav.indicator-height', 26),
    dimension('bottom-nav.indicator-radius', 999),
    dimension('bottom-nav.badge-size', 16),
    dimension('bottom-nav.badge-font-size', 10),
    numberAlias('bottom-nav.active-weight', 'font.weight-medium'),
    color('bottom-nav.bg', 'color.surface'),
    color('bottom-nav.border', 'color.border'),
    color('bottom-nav.inactive-text', 'color.text-secondary'),
    color('bottom-nav.active-text', 'color.text'),
    color('bottom-nav.indicator-bg', 'accent.9'),
    color('bottom-nav.indicator-text', 'accent.contrast'),
    color('bottom-nav.badge-bg', 'status.danger'),
    color('bottom-nav.badge-text', 'color.surface'),
    color('bottom-nav.focus-ring', 'color.focus-ring'),

    // Cards and content groups
    dimension('panel.width', 520),
    dimension('panel.padding', 18),
    dimension('panel.gap', 14),
    dimensionAlias('panel.radius', 'radius.container'),
    numberAlias('panel.title-weight', 'font.weight-semibold'),
    color('panel.bg', 'color.surface'),
    color('panel.text', 'color.text'),
    color('panel.secondary-text', 'color.text-secondary'),
    color('panel.border', 'color.border'),

    dimension('row.min-height', 56),
    dimension('row.padding-y', 8),
    dimension('row.gap', 12),
    dimension('row.content-gap', 2),
    dimension('row.icon-size', 42),
    dimension('row.icon-glyph-size', 20),
    color('row.text', 'color.text'),
    color('row.secondary-text', 'color.text-secondary'),
    color('row.border', 'color.border'),
    color('row.icon-bg', 'color.surface-muted'),
    color('row.focus-ring', 'color.focus-ring'),

    dimension('station-card.width', 560),
    dimension('station-card.padding', 16),
    dimension('station-card.gap', 14),
    dimensionAlias('station-card.radius', 'radius.container'),
    dimension('station-card.media-size', 56),
    dimensionAlias('station-card.media-radius', 'radius.interactive'),
    dimension('station-card.media-font-size', 24),
    dimension('station-card.content-gap', 5),
    dimension('station-card.distance-padding-x', 10),
    dimension('station-card.distance-padding-y', 7),
    dimension('station-card.distance-radius', 999),
    dimensionAlias('station-card.distance-font-size', 'text.caption'),
    color('station-card.bg', 'color.surface'),
    color('station-card.text', 'color.text'),
    color('station-card.secondary-text', 'color.text-secondary'),
    color('station-card.border', 'color.border'),
    color('station-card.media-bg', 'color.surface-muted'),
    color('station-card.distance-bg', 'color.surface-muted'),
    color('station-card.focus-ring', 'color.focus-ring'),

    dimension('map-marker.min-width', 48),
    dimension('map-marker.min-height', 44),
    dimension('map-marker.padding-x', 9),
    dimension('map-marker.padding-y', 3),
    dimension('map-marker.radius', 14),
    dimension('map-marker.tail-radius', 4),
    dimensionAlias('map-marker.label-font-size', 'text.caption'),
    color('map-marker.available-bg', 'status.success'),
    color('map-marker.unavailable-bg', 'status.danger'),
    color('map-marker.unknown-bg', 'color.text-secondary'),
    color('map-marker.text', 'color.surface'),
    color('map-marker.border', 'color.surface'),
    color('map-marker.focus-ring', 'color.focus-ring'),
    shadow('map-marker.shadow', 'elevation.floating'),
    duration('map-marker.transition-duration', 'motion.interaction.duration'),
    string('map-marker.transition-easing', 'motion.interaction.easing'),

    dimension('option-list.width', 520),
    dimension('option-list.gap', 12),
    dimension('option-list.item-height', 58),
    dimension('option-list.item-padding-x', 14),
    dimension('option-list.item-padding-y', 10),
    dimensionAlias('option-list.item-radius', 'radius.interactive'),
    dimension('option-list.icon-size', 44),
    dimension('option-list.indicator-size', 24),
    dimensionAlias('option-list.value-font-size', 'text.heading'),
    color('option-list.item-bg', 'color.surface'),
    color('option-list.item-border', 'color.border'),
    color('option-list.item-selected-bg', 'color.surface-muted'),
    color('option-list.item-selected-border', 'accent.9'),
    color('option-list.icon-bg', 'color.surface-muted'),
    color('option-list.indicator-bg', 'accent.9'),
    color('option-list.indicator-text', 'accent.contrast'),
    color('option-list.item-disabled-bg', 'color.surface-muted'),
    color('option-list.secondary-text', 'color.text-secondary'),
    color('option-list.disabled-text', 'color.text-secondary'),
    color('option-list.accent', 'accent.9'),
    color('option-list.focus-ring', 'color.focus-ring'),
    dimension('slider.track-height', 6),
    dimension('slider.thumb-size', 24),
    dimension('slider.radius', 999),
    color('slider.track-bg', 'color.border'),
    color('slider.range-bg', 'accent.9'),
    color('slider.thumb-bg', 'color.surface'),
    color('slider.thumb-border', 'accent.9'),
    color('slider.focus-ring', 'color.focus-ring'),

    dimension('command-progress.width', 480),
    dimension('command-progress.padding', 18),
    dimension('command-progress.gap', 14),
    dimensionAlias('command-progress.radius', 'radius.container'),
    color('command-progress.bg', 'color.surface'),
    color('command-progress.connector', 'color.border'),

    dimension('accordion.width', 520),
    dimension('accordion.padding-y', 14),
    numberAlias('accordion.title-weight', 'font.weight-medium'),
    color('accordion.border', 'color.border'),
    color('accordion.secondary-text', 'color.text-secondary'),
    color('accordion.focus-ring', 'color.focus-ring'),
    duration('accordion.transition-duration', 'motion.interaction.duration'),
    string('accordion.transition-easing', 'motion.interaction.easing'),

    dimension('support-tile.width', 240),
    dimension('support-tile.padding', 18),
    dimension('support-tile.gap', 5),
    dimensionAlias('support-tile.radius', 'radius.container'),
    dimension('support-tile.icon-size', 44),
    dimension('support-tile.icon-font-size', 20),
    color('support-tile.bg', 'color.surface'),
    color('support-tile.border', 'color.border'),
    color('support-tile.failed-border', 'status.danger'),
    color('support-tile.icon-bg', 'color.surface-muted'),
    color('support-tile.secondary-text', 'color.text-secondary'),
    color('support-tile.focus-ring', 'color.focus-ring'),
    duration('support-tile.transition-duration', 'motion.interaction.duration'),
    string('support-tile.transition-easing', 'motion.interaction.easing'),

    dimension('step-guide.gap', 14),
    dimension('step-guide.item-gap', 12),
    dimension('step-guide.icon-size', 30),
    color('step-guide.inactive-text', 'color.text-secondary'),
    color('step-guide.active-text', 'color.text'),
    color('step-guide.icon-border', 'color.border'),
    color('step-guide.complete-bg', 'accent.9'),
    color('step-guide.complete-text', 'accent.contrast'),

    // Composed overlays and screens
    dimension('orientation-card.width', 300),
    dimension('orientation-card.gap', 10),
    dimension('orientation-card.media-padding', 20),
    dimensionAlias('orientation-card.media-radius', 'radius.overlay'),
    dimensionAlias('orientation-card.media-font-size', 'text.heading'),
    dimensionAlias('orientation-card.caption-font-size', 'text.caption'),
    numberAlias('orientation-card.media-weight', 'font.weight-bold'),
    color('orientation-card.media-bg', 'accent.9'),
    color('orientation-card.media-text', 'accent.contrast'),
    color('orientation-card.secondary-text', 'color.text-secondary'),
    color('orientation-card.surface', 'color.surface'),

    dimension('sheet.width', 390),
    dimension('sheet.gap', 16),
    dimension('sheet.padding-top', 10),
    dimension('sheet.padding-x', 20),
    dimension('sheet.padding-bottom', 24),
    dimensionAlias('sheet.radius', 'radius.overlay'),
    dimension('sheet.grabber-width', 38),
    dimension('sheet.grabber-height', 4),
    dimension('sheet.grabber-radius', 999),
    dimension('sheet.action-gap', 10),
    dimensionAlias('sheet.title-size', 'text.heading'),
    numberAlias('sheet.title-weight', 'font.weight-semibold'),
    color('sheet.bg', 'color.bg'),
    color('sheet.text', 'color.text'),
    color('sheet.secondary-text', 'color.text-secondary'),
    color('sheet.grabber-bg', 'color.border-strong'),
    color('sheet.overlay-bg', 'color.overlay'),
    shadow('sheet.shadow', 'elevation.sheet'),
    duration('sheet.transition-duration', 'motion.swap.duration'),
    string('sheet.transition-easing', 'motion.swap.easing'),

    dimension('screen.width', 390),
    dimension('screen.min-height', 640),
    dimension('screen.gap', 18),
    dimension('screen.padding-top', 18),
    dimension('screen.padding-x', 20),
    dimension('screen.padding-bottom', 24),
    dimension('screen.wordmark-font-size', 44),
    dimension('screen.wordmark-subtitle-font-size', 18),
    numberAlias('screen.wordmark-weight', 'font.weight-bold'),
    color('screen.bg', 'color.bg'),
    color('screen.text', 'color.text'),
    color('screen.secondary-text', 'color.text-secondary'),

    dimensionAlias('scanner.viewport-radius', 'radius.overlay'),
    dimension('scanner.corner-inset', 24),
    dimension('scanner.corner-stroke', 3),
    dimension('scanner.corner-radius', 24),
    dimension('scanner.beam-inset', 20),
    dimension('scanner.beam-height', 2),
    dimension('scanner.action-gap', 12),
    color('scanner.viewport-bg', 'color.surface'),
    color('scanner.viewport-border', 'color.border'),
    color('scanner.accent', 'accent.9'),
    color('scanner.secondary-text', 'color.text-secondary'),
    duration('scanner.duration', 'motion.scanner.duration'),
    string('scanner.easing', 'motion.swap.easing'),

    dimension('charger-detail.width', 390),
    dimension('charger-detail.min-height', 720),
    dimension('charger-detail.map-height', 300),
    dimension('charger-detail.sheet-max-height', 600),
    dimension('charger-detail.sheet-gap', 14),
    dimension('charger-detail.sheet-padding-top', 10),
    dimension('charger-detail.sheet-padding-x', 20),
    dimension('charger-detail.sheet-padding-bottom', 24),
    dimensionAlias('charger-detail.sheet-radius', 'radius.overlay'),
    dimension('charger-detail.map-label-padding-x', 12),
    dimension('charger-detail.map-label-padding-y', 8),
    dimension('charger-detail.map-label-radius', 999),
    color('charger-detail.bg', 'color.bg'),
    color('charger-detail.map-bg', 'color.surface'),
    color('charger-detail.map-pattern', 'color.surface-muted'),
    color('charger-detail.map-line', 'color.border'),
    color('charger-detail.map-road', 'color.bg'),
    color('charger-detail.map-text', 'color.text-secondary'),
    color('charger-detail.map-label-bg', 'color.surface'),
    shadow('charger-detail.map-label-shadow', 'elevation.floating'),
    shadow('charger-detail.sheet-shadow', 'elevation.sheet'),

    dimension('session.metric-padding-y', 28),
    dimensionAlias('session.metric-font-size', 'text.display'),
    dimension('session.stats-gap', 10),
    dimension('session.stat-gap', 4),
    dimension('session.stat-padding', 14),
    dimensionAlias('session.stat-radius', 'radius.interactive'),
    dimension('session.actions-gap', 10),
    dimensionAlias('session.summary-font-size', 'text.heading'),
    color('session.metric-secondary-text', 'color.text-secondary'),
    color('session.stat-bg', 'color.surface'),
    color('session.stat-secondary-text', 'color.text-secondary'),

    // Catalogue-only composition tokens keep the demo independent of product slots.
    dimension('catalogue.cell-min-width', 280),
    dimension('catalogue.grid-gap', 16),
    dimension('catalogue.cell-gap', 12),
    dimension('catalogue.cell-padding', 16),
    dimensionAlias('catalogue.cell-radius', 'radius.container'),
    dimensionAlias('catalogue.label-font-size', 'text.caption'),
    numberAlias('catalogue.label-weight', 'font.weight-medium'),
    color('catalogue.cell-bg', 'color.bg'),
    color('catalogue.cell-text', 'color.text'),
    color('catalogue.cell-border', 'color.border'),
    color('catalogue.label-text', 'color.text-secondary'),
    color('catalogue.rating-idle', 'color.border-strong'),
    color('catalogue.rating-selected', 'status.warning'),
    color('catalogue.focus-ring', 'color.focus-ring'),
  ],
};
